# Descrizione delle Alpi

+ Le Alpi sono una catena montuosa situata nella parte settentrionale dell'Italia e segnano i confini terrestri dello Stato.
+ Si dividono in varie sezioni che sono 
- *Alpi Giulie*
- *Alpi Graie*
- *Alpi Cozie*
  - ecc.
- La vetta più alta è il Monte Bianco, 4400 metri circa.
